version: '3.5'
services:
    angular-service:
      container_name: angular_container
      build: ./frontend
      volumes:
        - './frontend:/usr/src/app' 
      ports: 
        - '4200:4200'
      command: > 
        bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    php_apache:
      image: php:7.2-apache
      ports:
        - 80:80
      volumes:
        - './backend:/var/www/html'
    mysql:
      image: mysql
      # restart: always
      ports:
        - 33060:33060
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - './mysql-data:/var/lib/mysql'
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links: 
        - mysql:db
      ports:
      #  - 8765:80
        - 8081:80
      environment:
        MYSQL_ROOT_PASSWORD: root
      depends_on:
        - mysql
