version: '3.5'
services:
    frontend:
      build: ./frontend
      volumes:
        - './frontend:/usr/src/app' 
      ports: 
        - '4200:4200'
    backend:
      build: ./backend
      ports:
        - 80:80
      volumes:
        - './backend:/var/www/html'
    mysql:
      image: mysql
      ports:
        - 33060:33060
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - './mysql-data:/var/lib/mysql'
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - 8081:80
      environment:
        PMA_HOST: mysql
        MYSQL_ROOT_PASSWORD: root
      depends_on:
        - mysql
